const menuBtn=document.getElementById('menuBtn');const nav=document.getElementById('nav');menuBtn?.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
window.addEventListener('load',()=>setTimeout(()=>document.getElementById('loader')?.classList.add('hide'),450));window.addEventListener('scroll',()=>document.querySelector('.site-header')?.classList.toggle('scrolled',scrollY>20));
const glow=document.querySelector('.cursor-glow');window.addEventListener('mousemove',e=>{if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');if(e.target.classList.contains('stats'))startCounters();}})},{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
let counted=false;function startCounters(){if(counted)return;counted=true;document.querySelectorAll('.counter').forEach(el=>{const target=+el.dataset.target;let cur=0;const step=Math.max(1,Math.round(target/40));const tick=()=>{cur+=step;if(cur>=target){el.textContent=target;return}el.textContent=cur;requestAnimationFrame(tick)};tick();});}
const form=document.getElementById('quoteForm');form?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const msg=`Hi Tarun, I want a free quote.%0A%0AName: ${data.get('name')}%0ABusiness: ${data.get('business')}%0APhone: ${data.get('phone')}%0AEmail: ${data.get('email')}%0AService: ${data.get('service')}%0ABudget: ${data.get('budget')}%0ADetails: ${data.get('details')}`;alert('Thank you! WhatsApp par inquiry open ho rahi hai.');window.open('https://wa.me/918191948181?text='+msg,'_blank')});
// Filters
const tabs=document.querySelectorAll('.work-tabs button');const cards=document.querySelectorAll('.project-card');tabs.forEach(btn=>btn.addEventListener('click',()=>{tabs.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;cards.forEach(card=>{const show=f==='all'||(card.dataset.category||'').includes(f);card.style.display=show?'block':'none';});}));
// Project folders modal
const modal=document.getElementById('projectModal'),modalTitle=document.getElementById('modalTitle'),modalDesc=document.getElementById('modalDesc'),modalGallery=document.getElementById('modalGallery');document.querySelectorAll('[data-folder]').forEach(card=>{card.addEventListener('click',()=>openFolder(card.dataset.folder));});function openFolder(name){const imgs=(window.PROJECTS&&window.PROJECTS[name])||[];modalTitle.textContent=name;modalDesc.textContent=`${imgs.length} designs in this project folder`;modalGallery.innerHTML=imgs.map((src,i)=>`<a href="${src}" target="_blank" title="Open image"><img loading="lazy" src="${src}" alt="${name} design ${i+1}"></a>`).join('')||'<p>No images added yet.</p>';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
modal?.addEventListener('click',e=>{if(e.target.dataset.close==='true')closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});function closeModal(){modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');document.body.style.overflow='';}
// Tilt effect
function attachTilt(el){el.addEventListener('mousemove',e=>{if(innerWidth<900)return;const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateX(${(-y*4).toFixed(2)}deg) rotateY(${(x*4).toFixed(2)}deg) translateY(-4px)`});el.addEventListener('mouseleave',()=>{el.style.transform='';});}document.querySelectorAll('[data-tilt]').forEach(attachTilt);

// Scroll progress
const scrollProgress=document.getElementById('scrollProgress');window.addEventListener('scroll',()=>{if(scrollProgress){const h=document.documentElement.scrollHeight-innerHeight;scrollProgress.style.width=(h?scrollY/h*100:0)+'%';}});
// Stagger reveals
const revealGroups=[...document.querySelectorAll('.service-grid,.project-grid')];revealGroups.forEach(group=>[...group.children].forEach((child,i)=>child.style.transitionDelay=(i*0.06)+'s'));
// AI Assistant
const aiToggle=document.getElementById('aiToggle'),aiPanel=document.getElementById('aiPanel'),aiClose=document.getElementById('aiClose'),aiMessages=document.getElementById('aiMessages'),aiOptions=document.getElementById('aiOptions'),aiWhatsapp=document.getElementById('aiWhatsapp');let selectedService='';const aiReplies={
'Logo Design':'Logo Design ke liye I can help with logo concept, color palette, typography and brand presentation. Best for new businesses and Instagram brands.',
'Website Design':'Website Design me business website, portfolio, landing page, product selling website, WhatsApp button and contact form setup include ho sakta hai.',
'Instagram Handling':'Instagram Handling me content planning, post design, reel covers, stories, captions and profile optimization cover hoga.',
'Packaging Design':'Packaging Design me product label, hang tag, sticker, catalogue and e-commerce listing images ban sakti hain.',
'Video & Reels':'Video & Reels me product reels, promo videos, motion posters, reel editing and text animation videos ban sakte hain.',
'Pricing & Packages':'Pricing project type par depend karti hai. Aap service select karke name/phone bhej do, Tarun aapko free quote de dega.'
};
aiToggle?.addEventListener('click',()=>aiPanel.classList.toggle('open'));aiClose?.addEventListener('click',()=>aiPanel.classList.remove('open'));
aiOptions?.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;selectedService=e.target.dataset.service;aiMessages.insertAdjacentHTML('beforeend',`<div class="user-msg">${selectedService}</div><div class="bot-msg">${aiReplies[selectedService]}<br><br>Apna name aur phone number add karo, main WhatsApp inquiry ready kar dunga.</div>`);aiMessages.scrollTop=aiMessages.scrollHeight;});
aiWhatsapp?.addEventListener('click',()=>{const name=document.getElementById('aiName').value||'Client';const phone=document.getElementById('aiPhone').value||'';const service=selectedService||'Design / Website Service';const text=`Hi Tarun, I came from your portfolio website.%0A%0AName: ${encodeURIComponent(name)}%0APhone: ${encodeURIComponent(phone)}%0AService Required: ${encodeURIComponent(service)}%0A%0APlease share details and pricing.`;window.open('https://wa.me/918191948181?text='+text,'_blank');});
// Open chatbot from elements if needed
window.openTarunAI=()=>aiPanel?.classList.add('open');
